#!/usr/bin/env node
// Spec gate, part of `pnpm check`. Runs the repo's pinned OpenSpec — never a global one — and also fails on
// what `openspec validate` lets through on its own:
//   1. `validate --all --strict` exits 0 on an empty tree, so green on nothing proves nothing;
//   2. `archive -y` archives a change with unfinished tasks — `validate --archived` catches that afterwards;
//   3. a skill or /opsx command that calls a bare `openspec` (e.g. regenerated by `openspec update`).
import { spawnSync } from "node:child_process";
import { existsSync, readdirSync, readFileSync } from "node:fs";
import { join, relative } from "node:path";
import { BARE_CALL, generatedFiles } from "./openspec-pin.mjs";

const cli = join("node_modules", "@fission-ai", "openspec", "bin", "openspec.js");
const failures = [];

if (!existsSync(cli)) {
  console.error("spec:check: pinned OpenSpec not installed — run `pnpm install`.");
  process.exit(1);
}

function openspec(args) {
  const r = spawnSync(process.execPath, [cli, ...args], {
    encoding: "utf8",
    env: { ...process.env, OPENSPEC_TELEMETRY: "0", NO_COLOR: "1" },
  });
  return { code: r.status ?? 1, out: `${r.stdout ?? ""}${r.stderr ?? ""}`.trim() };
}

const dirs = (p) => (existsSync(p) ? readdirSync(p, { withFileTypes: true }).filter((d) => d.isDirectory()).map((d) => d.name) : []);
const specs = dirs(join("openspec", "specs"));
const active = dirs(join("openspec", "changes")).filter((d) => d !== "archive");
const archived = dirs(join("openspec", "changes", "archive"));

const all = openspec(["validate", "--all", "--strict", "--no-interactive"]);
if (all.code !== 0) failures.push(`openspec validate --all --strict (exit ${all.code})\n${all.out}`);

if (archived.length > 0) {
  const arch = openspec(["validate", "--archived", "--no-interactive"]);
  if (arch.code !== 0) failures.push(`openspec validate --archived (exit ${arch.code})\n${arch.out}`);
  if (specs.length === 0) failures.push(`${archived.length} archived change(s) but openspec/specs/ is empty — the archive did not produce a spec.`);
}

for (const file of generatedFiles()) {
  readFileSync(file, "utf8").split("\n").forEach((line, i) => {
    if (line.match(BARE_CALL)) failures.push(`bare \`openspec\` call — run \`pnpm openspec:pin\`: ${relative(process.cwd(), file).replaceAll("\\", "/")}:${i + 1}`);
  });
}

if (failures.length > 0) {
  console.error(`spec:check FAILED\n\n${failures.join("\n\n")}`);
  process.exit(1);
}
console.log(`spec:check ok — specs: ${specs.length} · active changes: ${active.length} · archived: ${archived.length}`);
